# Generated by Django 4.1 on 2022-08-09 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checklist', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='procedure',
            name='step',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
    ]
