# Generated by Django 4.1 on 2022-08-12 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checklist', '0004_procedure_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='procedure',
            name='slug',
            field=models.SlugField(unique=True),
        ),
    ]
