# Generated by Django 4.1 on 2022-08-12 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checklist', '0005_alter_procedure_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='SessionProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attributes', models.ManyToManyField(blank=True, to='checklist.attribute')),
            ],
        ),
    ]
