# Generated by Django 4.1 on 2022-08-30 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checklist', '0007_sessionprofile_sessionid'),
    ]

    operations = [
        migrations.AddField(
            model_name='attribute',
            name='description',
            field=models.TextField(blank=True),
        ),
    ]
