# Generated by Django 4.1 on 2022-08-31 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checklist', '0009_attribute_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='checkitem',
            name='step',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
    ]
