# Generated by Django 4.1 on 2023-07-22 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checklist', '0011_alter_checkitem_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sessionprofile',
            name='sessionId',
        ),
        migrations.AddField(
            model_name='sessionprofile',
            name='sessionKey',
            field=models.CharField(default='default', max_length=32),
            preserve_default=False,
        ),
    ]
