# Generated by Django 4.1 on 2023-07-25 21:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('checklist', '0012_remove_sessionprofile_sessionid_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SessionProfile',
        ),
    ]
