# Generated by Django 4.1 on 2023-09-19 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checklist', '0013_delete_sessionprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='attribute',
            name='show',
            field=models.BooleanField(default='True'),
        ),
    ]
