# Generated by Django 4.1 on 2023-10-10 09:01

import colorfield.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('checklist', '0015_attribute_over_ruled_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='attribute',
            name='btn_color',
            field=colorfield.fields.ColorField(default='194D33', image_field=None, max_length=25, samples=None),
        ),
    ]
