# Generated by Django 4.1 on 2024-06-29 18:06

import colorfield.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checklist', '0016_attribute_btn_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='checkitem',
            name='action_label',
            field=models.CharField(blank=True, max_length=8),
        ),
        migrations.AddField(
            model_name='checkitem',
            name='dataref_expression',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='procedure',
            name='show_expression',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='attribute',
            name='btn_color',
            field=colorfield.fields.ColorField(default='#194D33', image_field=None, max_length=25, samples=None),
        ),
    ]
