# Generated by Django 4.1 on 2025-04-07 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checklist', '0018_procedure_auto_continue'),
    ]

    operations = [
        migrations.AddField(
            model_name='checkitem',
            name='role',
            field=models.CharField(blank=True, choices=[('PF', 'Pilot Flying'), ('PM', 'Pilot Monitoring'), ('C', 'Captain'), ('BOTH', 'Both'), ('FO', 'First Officer')], default='', help_text='Indicates who should perform this check item.', max_length=10),
        ),
    ]
