# Generated by Django 5.2.1 on 2026-03-19 22:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checklist', '0019_checkitem_role'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    def _backfill_profiles(apps, schema_editor):
        User = apps.get_model(settings.AUTH_USER_MODEL)
        UserProfile = apps.get_model("checklist", "UserProfile")
        for user in User.objects.all():
            UserProfile.objects.get_or_create(user=user)

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('simbrief_id', models.CharField(blank=True, max_length=20)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RunPython(_backfill_profiles, migrations.RunPython.noop),
    ]
