# Generated by Django 5.2.1 on 2026-03-21 14:39

import checklist.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checklist', '0020_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='checkitem',
            name='auto_check_rule',
            field=models.JSONField(blank=True, help_text='v2.0 auto-check rule (JSON). Do not modify dataref_expression.', null=True),
        ),
        migrations.CreateModel(
            name='FlightSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_key', models.CharField(default=checklist.models._generate_session_key, help_text='Short code shown to pilot (e.g. A3F2-0891).', max_length=20, unique=True)),
                ('pilot_role', models.CharField(choices=[('PF', 'Pilot Flying'), ('PM', 'Pilot Monitoring'), ('SOLO', 'Solo')], default='SOLO', max_length=10)),
                ('pilot_function', models.CharField(choices=[('C', 'Captain'), ('FO', 'First Officer'), ('BOTH', 'Both')], default='BOTH', max_length=10)),
                ('active_phase', models.CharField(blank=True, max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_plugin_contact', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('user_profile', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='flight_sessions', to='checklist.userprofile')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='FlightInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('origin_icao', models.CharField(max_length=10)),
                ('destination_icao', models.CharField(max_length=10)),
                ('alternate_icao', models.CharField(blank=True, max_length=10)),
                ('oat', models.IntegerField(blank=True, help_text='Outside air temp °C', null=True)),
                ('departure_runway', models.CharField(blank=True, max_length=10)),
                ('departure_stand', models.CharField(blank=True, max_length=20)),
                ('fuel_on_board', models.IntegerField(blank=True, help_text='kg', null=True)),
                ('ofp_loaded', models.BooleanField(default=False)),
                ('flight_session', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='flight_info', to='checklist.flightsession')),
            ],
        ),
        migrations.CreateModel(
            name='FlightItemState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('checked', 'Checked'), ('skipped', 'Skipped'), ('pending', 'Pending')], max_length=10)),
                ('source', models.CharField(blank=True, choices=[('manual', 'Manual'), ('auto', 'Auto')], max_length=10, null=True)),
                ('checked_at', models.DateTimeField(blank=True, null=True)),
                ('checklist_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='checklist.checkitem')),
                ('flight_session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='item_states', to='checklist.flightsession')),
            ],
            options={
                'unique_together': {('flight_session', 'checklist_item')},
            },
        ),
        migrations.CreateModel(
            name='FlightSessionAttribute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=False)),
                ('source', models.CharField(choices=[('user_default', 'User Default'), ('ofp_derived', 'OFP Derived'), ('pilot_override', 'Pilot Override')], default='user_default', max_length=20)),
                ('attribute', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='checklist.attribute')),
                ('flight_session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='session_attributes', to='checklist.flightsession')),
            ],
            options={
                'unique_together': {('flight_session', 'attribute')},
            },
        ),
    ]
