# Generated by Django 5.2.1 on 2026-03-21 18:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checklist', '0021_flight_session'),
    ]

    operations = [
        migrations.AddField(
            model_name='attribute',
            name='is_user_preference',
            field=models.BooleanField(default=False, help_text='Show this attribute on the account profile page as a saveable default.'),
        ),
        migrations.CreateModel(
            name='UserAttributeDefault',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attribute', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='checklist.attribute')),
                ('user_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attribute_defaults', to='checklist.userprofile')),
            ],
            options={
                'unique_together': {('user_profile', 'attribute')},
            },
        ),
    ]
