# Generated by Django 5.2.1 on 2026-03-23 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checklist', '0022_user_attribute_default'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='flightinfo',
            name='fuel_on_board',
        ),
        migrations.AddField(
            model_name='attribute',
            name='label',
            field=models.CharField(blank=True, help_text='User-facing display name shown in UI. Falls back to title when blank.', max_length=60),
        ),
        migrations.AddField(
            model_name='flightinfo',
            name='block_fuel_kg',
            field=models.IntegerField(blank=True, help_text='Block fuel in kg (plan_ramp)', null=True),
        ),
        migrations.AddField(
            model_name='flightinfo',
            name='callsign',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='flightinfo',
            name='finres_altn_kg',
            field=models.IntegerField(blank=True, help_text='FINRES+ALTN in kg', null=True),
        ),
        migrations.AddField(
            model_name='flightinfo',
            name='flaps_setting',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
