# Generated by Django 5.2.1 on 2026-03-26 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checklist', '0023_add_label_and_flightinfo_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='api_key_hash',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='api_key_prefix',
            field=models.CharField(blank=True, max_length=8, null=True),
        ),
    ]
