# Generated by Django 5.2.1 on 2026-04-15 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checklist', '0025_zibo_auto_check_rules'),
    ]

    operations = [
        migrations.AddField(
            model_name='attribute',
            name='live_rule',
            field=models.JSONField(blank=True, help_text='Dataref rule evaluated at procedure transitions to auto-activate or prompt.', null=True),
        ),
        migrations.AddField(
            model_name='attribute',
            name='live_rule_mode',
            field=models.CharField(blank=True, choices=[('activate_only', 'Activate Only'), ('prompt_on_change', 'Prompt on Change')], help_text='activate_only: apply silently. prompt_on_change: ask the pilot.', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='attribute',
            name='prompt_message',
            field=models.CharField(blank=True, help_text='Message shown to pilot when live_rule triggers in prompt_on_change mode.', max_length=200),
        ),
        migrations.AddField(
            model_name='flightsession',
            name='pilot_overrides',
            field=models.JSONField(blank=True, default=dict, help_text='Session-wide pilot decisions on live_rule suggestions. {str(attr_id): bool}'),
        ),
        migrations.AlterField(
            model_name='flightsessionattribute',
            name='source',
            field=models.CharField(choices=[('user_default', 'User Default'), ('ofp_derived', 'OFP Derived'), ('pilot_override', 'Pilot Override'), ('live_rule', 'Live Rule')], default='user_default', max_length=20),
        ),
    ]
