# Generated by Django 5.2.1 on 2026-04-19 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checklist', '0026_attribute_live_rule_attribute_live_rule_mode_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='IdleDataref',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=40)),
                ('dataref_path', models.CharField(max_length=200)),
                ('unit', models.CharField(blank=True, max_length=20)),
                ('value_map', models.JSONField(blank=True, help_text="Optional numeric-to-label mapping, e.g. {0: 'preflight', 1: 'taxi'}.", null=True)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.AddField(
            model_name='procedure',
            name='show_rule',
            field=models.JSONField(blank=True, help_text='Rule evaluated against live datarefs. When true, procedure appears in nav. Null = always visible.', null=True),
        ),
    ]
