# Generated by Django 5.2.1 on 2026-05-19 19:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checklist', '0030_procedure_sop_nonnullable'),
    ]

    operations = [
        migrations.CreateModel(
            name='RuleMissReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reported_at', models.DateTimeField(db_index=True)),
                ('reported_item_label', models.CharField(max_length=50)),
                ('active_phase', models.CharField(max_length=50)),
                ('rule', models.JSONField(blank=True, null=True)),
                ('leaf_evaluations', models.JSONField()),
                ('conditions_total', models.PositiveSmallIntegerField(default=0)),
                ('conditions_failing', models.PositiveSmallIntegerField(default=0)),
                ('plugin_version', models.CharField(blank=True, max_length=20)),
                ('flight_session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rule_miss_reports', to='checklist.flightsession')),
                ('reported_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rule_miss_reports', to='checklist.checkitem')),
            ],
            options={
                'ordering': ['-reported_at'],
            },
        ),
    ]
