# Generated by Django 5.2.1 on 2026-06-05 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checklist', '0031_rulemissreport'),
    ]

    operations = [
        migrations.AddField(
            model_name='flightsession',
            name='show_rule_state',
            field=models.JSONField(blank=True, default=dict, help_text='Last evaluated show_rule result per procedure: {str(proc.pk): bool}. Used for rising-edge detection in poll_view.'),
        ),
    ]
